
global with sharing class BadClass {
    
    private id myid;
    private id myid2;
    private id myid3;
    public List<User> bingos {get; private set;}
    private List<User> allusers;
    private Set<Id> userids;
    public User me {get; set;}
    public User user1 {get; set;}
    public User user2 {get; set;}
    public User user3 {get; set;}
    public User user4 {get; set;}
    public User user5 {get; set;}
    public User user6 {get; set;}
    public User user7 {get; set;}
    public User user8 {get; set;}
    public User user9 {get; set;}
    public User user10 {get; set;}
    public User user11 {get; set;}
    public User user12 {get; set;}
    public User user13 {get; set;}
    public User user14 {get; set;}
    public User user15 {get; set;}
    public User user16 {get; set;}
    public User user17 {get; set;}
    public User user18 {get; set;}
    public User user19 {get; set;}
    public User user20 {get; set;}
    public User user21 {get; set;}
    public User user22 {get; set;}
    public User user23 {get; set;}
    public User user24 {get; set;}
    public User user25 {get; set;}
    
    //public List<User> bingousers {get; set;}
    
    private static final integer totalsquares = 25;
    
	private static final integer querylimit = 10000;
    
    /**
     * The constructor for BingoController
     */
    
    public BadClass(){
	    
	    integer unusedVariable1 = 0;
	    integer unusedVariable2 = 0;
    }
}
